name: xMusic
main: org.eldrygo.XMusic.XMusic
version: 0.0.11
api-version: 1.20
authors:
  - Drygo
softdepend:
  - PlaceholderAPI
commands:
  xmusic:
    aliases:
      - xms
    description: "xMusic plugin administration command."
permissions:
  xmusic.admin:
    children:
      xmusic.command.play:
        default: false
        children:
          xmusic.command.play.song:
            default: false
          xmusic.command.play.playlist:
            default: false
      xmusic.command.stop:
        default: false
        children:
          xmusic.command.stop.song:
            default: false
          xmusic.command.stop.playlist:
            default: false
      xmusic.command.skip:
        default: false
      xmusic.command.reload:
        default: false